Updates airports.json File
Travelin-ai/airport-codes pull request #2
Opened 2022-12-01 13:46 UTC by ashok9180

2022-12-02 08:55 UTC, tah requested changes
A few points:
- Why are almost all lines in `airports.json` removed?
- Let's not commit the `package-lock.json` in a lib like this

2022-12-02 09:49 UTC, fullstackdeveloper918 commented
> Why are almost all lines in airports.json removed?

Because the old file is merged with new data .....through code.

> Let's not commit the package-lock.json in a lib like this

Sure

2022-12-03 08:02 UTC, tah reviewed
Could we combine/merge the `newConvert.js` script with `convert.js`?
1. Read and parse `.dat` file
2. Read and parse `.csv` file
3. Combine and reduce to unique entries
4. Write json file

2022-12-03 08:02 UTC, tah commented on package.json
>    "dependencies": {
These should all be `devDependencies` right? They are not needed when using and importing the lib.

2022-12-05 04:59 UTC, ashok9180 commented on package.json
>    "dependencies": {
Yeah you are right?

2022-12-05 08:50 UTC, tah approved these changes

2022-12-05 08:50 UTC, merged